---
title: "ggplot 1"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
```

Load in a dataset that we'll use often 

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


## Scatterplot

tmax vs. tmin 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

you can save ggplots

```{r}
## create a ggplot object and manipulate 
ggp_tmax_tmin = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

ggp_tmax_tmin
## able to save ggplot with ggsave()
```


## Let's fancy it up

Add ... color? lines? and other stuff?

```{r}
weather_df %>% 
## color allows to distinguish variables by color.
  
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.3) + 
## alpha blending -- what degree of transparency, 0 -- everthing clear
  geom_smooth(se = FALSE) ## Aids the eye in seeing patterns in the presence of overplotting

weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE) + 
  facet_grid(.~ name) ## forms a matrix of panels defined by row and column faceting variables
```


Let's make one more scatterplot.

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, size = prcp)) +
  geom_point(alpha = .3) + 
  facet_grid(.~ name) + 
  geom_smooth(se = FALSE) ## se = false --> gives standard error / ci around and se false sets it off. 
```

## Use data manipulation as part of this 

```{r}
weather_df %>% 
  filter(name == " CentralPark_NY") %>% 
  mutate(
    tmax = tmax * (9/5) + 32,
    tmin = tmin * (9/5) + 32
    ) %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```


## Stacking geoms


Which geoms do you want?

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_smooth()
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, y = tmin)) + 
  geom_bin_2d()
```

## Univariable plots

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() + 
  facet_grid(. ~ name) ## . ~ name --> facet grid everthing against name
```

Let's try some other plots....

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = .3) 
```


Still with `tmax` and `name`

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_boxplot()
```

Some people like violin plots????

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin()
```


What about ridges ....

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, y = name)) + 
  geom_density_ridges(alpha = 0.8, scale = .85)
```

